### ISSUE TITLE
ios initAudio() Error: no getUserMedia

### ISSUE THREAD

**Issue by ai2010** [tracktunes/ionic-recorder#136]
I'm trying to run the app in ios 10 but I got the error:

ios initAudio() Error: no getUserMedia

I think it's coming from providers/web-audio/record.ts  line 165. Do you know how to solve the problem? 
Thanks a lot

**Comment by dorontal** [comment]
Apple does not support getUserMedia at this time. See
https://stackoverflow.com/questions/37258597/html5-getusermedia-ios-issue
and this webRTC link that'll tell you when Apple starts supporting the standard (getUserMedia is part of webRTC):
https://caniuse.com/#search=webrtc

Standards are good.  They encourage fair -- merit-based -- competition. 

Possible solution: use cordova-plugin-media -- up till recently it did not have the functionality needed for this app but now it seems to have it -- will look into using it as a replacement.

**Comment by dorontal** [comment]
Hmmm but I'm curious if you've tried chrome on iOS?  I suppose the above report was with Safari on iOS, right?  Would love to know if Chrome works on iOS.

**Comment by dorontal** [comment]
See http://caniuse.com/#feat=stream -- it may be solved in Safari 11. Closing for now because there is nothing that can be done about this.
