### ISSUE TITLE
I'm getting an error as "Stop playback. If an argument is supplied it is where you want"

### ISSUE THREAD

**Issue by BUHARIMOHAMEDISMAIL** [tracktunes/ionic-recorder#159]
I cloned repository and installed all the dependency.
After I installed i run the application using the command "ionic serve"
I'm getting error as "Stop playback. If an argument is supplied it is where you want"
Please assist me

**Comment by dorontal** [comment]
I'm not sure I understand where you see the error. 

The text "Stop playback.." is sitting inside a comment in the code.

Which version did you try?

**Comment by dorontal** [comment]
Closing this issue: while this project is in alpha phase all issues about things not working are invalid - expect nothing to work until the first beta version. Thank you for your participation.
